version: '3'

services:
  phpapache:
    build:
      context: './php/'
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
